namespace Urna
{
    partial class Form1{
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing){
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }
        private void init_comp(){
            textBoxDisplay = new TextBox();
            button1 = new Button();
            button2 = new Button();
            button3 = new Button();
            button4 = new Button();
            button5 = new Button();
            button6 = new Button();
            button7 = new Button();
            button8 = new Button();
            button9 = new Button();
            button0 = new Button();
            buttonBranco = new Button();
            buttonCorrige = new Button();
            buttonConfirma = new Button();
            pictureBox1 = new PictureBox();
            pictureBox2 = new PictureBox();
            textBox1 = new TextBox();
            pictureBox3 = new PictureBox();
            textBox2 = new TextBox();
            textBox3 = new TextBox();
            labelCargoAtual = new Label();
            ((System.ComponentModel.ISupportInitialize)pictureBox1).BeginInit();
            ((System.ComponentModel.ISupportInitialize)pictureBox2).BeginInit();
            ((System.ComponentModel.ISupportInitialize)pictureBox3).BeginInit();
            SuspendLayout();
            textBoxDisplay.Font = new Font("Microsoft Sans Serif", 16F);
            textBoxDisplay.Location = new Point(313, 111);
            textBoxDisplay.Name = "textBoxDisplay";
            textBoxDisplay.ReadOnly = true;
            textBoxDisplay.Size = new Size(123, 32);
            textBoxDisplay.TabIndex = 0;
            textBoxDisplay.TextAlign = HorizontalAlignment.Center;
            button1.BackColor = Color.Gray;
            button1.FlatStyle = FlatStyle.Popup;
            button1.Font = new Font("Segoe UI", 18F);
            button1.ForeColor = SystemColors.ButtonHighlight;
            button1.Location = new Point(792, 123);
            button1.Name = "button1";
            button1.Size = new Size(58, 40);
            button1.TabIndex = 1;
            button1.Text = "1";
            button1.UseVisualStyleBackColor = false;
            button1.Click += numeroButton_Click;
            button2.BackColor = Color.Gray;
            button2.FlatStyle = FlatStyle.Popup;
            button2.Font = new Font("Segoe UI", 18F);
            button2.ForeColor = SystemColors.ButtonHighlight;
            button2.Location = new Point(856, 123);
            button2.Name = "button2";
            button2.Size = new Size(58, 40);
            button2.TabIndex = 2;
            button2.Text = "2";
            button2.UseVisualStyleBackColor = false;
            button2.Click += numeroButton_Click;
            button3.BackColor = Color.Gray;
            button3.FlatStyle = FlatStyle.Popup;
            button3.Font = new Font("Segoe UI", 18F);
            button3.ForeColor = SystemColors.ButtonHighlight;
            button3.Location = new Point(920, 123);
            button3.Name = "button3";
            button3.Size = new Size(58, 40);
            button3.TabIndex = 3;
            button3.Text = "3";
            button3.UseVisualStyleBackColor = false;
            button3.Click += numeroButton_Click;
            button4.BackColor = Color.Gray;
            button4.FlatStyle = FlatStyle.Popup;
            button4.Font = new Font("Segoe UI", 18F);
            button4.ForeColor = SystemColors.ButtonHighlight;
            button4.Location = new Point(792, 169);
            button4.Name = "button4";
            button4.Size = new Size(58, 40);
            button4.TabIndex = 4;
            button4.Text = "4";
            button4.UseVisualStyleBackColor = false;
            button4.Click += numeroButton_Click;
            button5.BackColor = Color.Gray;
            button5.FlatStyle = FlatStyle.Popup;
            button5.Font = new Font("Segoe UI", 18F);
            button5.ForeColor = SystemColors.ButtonHighlight;
            button5.Location = new Point(856, 169);
            button5.Name = "button5";
            button5.Size = new Size(58, 40);
            button5.TabIndex = 5;
            button5.Text = "5";
            button5.UseVisualStyleBackColor = false;
            button5.Click += numeroButton_Click;
            button6.BackColor = Color.Gray;
            button6.FlatStyle = FlatStyle.Popup;
            button6.Font = new Font("Segoe UI", 18F);
            button6.ForeColor = SystemColors.ControlLightLight;
            button6.Location = new Point(920, 169);
            button6.Name = "button6";
            button6.Size = new Size(58, 40);
            button6.TabIndex = 6;
            button6.Text = "6";
            button6.UseVisualStyleBackColor = false;
            button6.Click += numeroButton_Click;
            button7.BackColor = Color.Gray;
            button7.FlatStyle = FlatStyle.Popup;
            button7.Font = new Font("Segoe UI", 18F);
            button7.ForeColor = SystemColors.ButtonHighlight;
            button7.Location = new Point(792, 215);
            button7.Name = "button7";
            button7.Size = new Size(58, 40);
            button7.TabIndex = 7;
            button7.Text = "7";
            button7.UseVisualStyleBackColor = false;
            button7.Click += numeroButton_Click;
            button8.BackColor = Color.Gray;
            button8.FlatStyle = FlatStyle.Popup;
            button8.Font = new Font("Segoe UI", 18F);
            button8.ForeColor = SystemColors.ControlLightLight;
            button8.Location = new Point(856, 215);
            button8.Name = "button8";
            button8.Size = new Size(58, 40);
            button8.TabIndex = 8;
            button8.Text = "8";
            button8.UseVisualStyleBackColor = false;
            button8.Click += numeroButton_Click;
            button9.BackColor = Color.Gray;
            button9.FlatStyle = FlatStyle.Popup;
            button9.Font = new Font("Segoe UI", 18F);
            button9.ForeColor = SystemColors.ControlLightLight;
            button9.Location = new Point(920, 215);
            button9.Name = "button9";
            button9.Size = new Size(58, 40);
            button9.TabIndex = 9;
            button9.Text = "9";
            button9.UseVisualStyleBackColor = false;
            button9.Click += numeroButton_Click;
            button0.BackColor = Color.Gray;
            button0.FlatStyle = FlatStyle.Popup;
            button0.Font = new Font("Segoe UI", 18F);
            button0.ForeColor = SystemColors.ControlLightLight;
            button0.Location = new Point(856, 261);
            button0.Name = "button0";
            button0.Size = new Size(58, 40);
            button0.TabIndex = 10;
            button0.Text = "0";
            button0.UseVisualStyleBackColor = false;
            button0.Click += numeroButton_Click;
            buttonBranco.BackColor = Color.White;
            buttonBranco.FlatStyle = FlatStyle.Flat;
            buttonBranco.Location = new Point(788, 335);
            buttonBranco.Name = "buttonBranco";
            buttonBranco.Size = new Size(60, 40);
            buttonBranco.TabIndex = 11;
            buttonBranco.Text = "Branco";
            buttonBranco.UseVisualStyleBackColor = false;
            buttonBranco.Click += buttonBranco_Click;
            buttonCorrige.BackColor = Color.FromArgb(255, 128, 0);
            buttonCorrige.FlatStyle = FlatStyle.Flat;
            buttonCorrige.Location = new Point(854, 335);
            buttonCorrige.Name = "buttonCorrige";
            buttonCorrige.Size = new Size(60, 40);
            buttonCorrige.TabIndex = 12;
            buttonCorrige.Text = "Corrige";
            buttonCorrige.UseVisualStyleBackColor = false;
            buttonCorrige.Click += buttonCorrige_Click;
            buttonConfirma.BackColor = Color.Lime;
            buttonConfirma.FlatStyle = FlatStyle.Flat;
            buttonConfirma.Location = new Point(920, 316);
            buttonConfirma.Name = "buttonConfirma";
            buttonConfirma.Size = new Size(80, 59);
            buttonConfirma.TabIndex = 13;
            buttonConfirma.Text = "Confirma";
            buttonConfirma.UseVisualStyleBackColor = false;
            buttonConfirma.Click += buttonConfirma_Click; 
            pictureBox1.BackColor = Color.FromArgb(64, 64, 64);
            pictureBox1.Location = new Point(735, -17);
            pictureBox1.Name = "pictureBox1";
            pictureBox1.Size = new Size(295, 431);
            pictureBox1.TabIndex = 14;
            pictureBox1.TabStop = false;
            pictureBox1.Click += pictureBox1_Click;
            pictureBox2.BackColor = Color.FromArgb(224, 224, 224);
            pictureBox2.Location = new Point(69, 64);
            pictureBox2.Name = "pictureBox2";
            pictureBox2.Size = new Size(610, 299);
            pictureBox2.TabIndex = 15;
            pictureBox2.TabStop = false;
            pictureBox2.Click += pictureBox2_Click;
            textBox1.BackColor = Color.FromArgb(255, 224, 192);
            textBox1.BorderStyle = BorderStyle.None;
            textBox1.Font = new Font("Arial Black", 12F);
            textBox1.Location = new Point(23, 22);
            textBox1.Name = "textBox1";
            textBox1.Size = new Size(189, 23);
            textBox1.TabIndex = 16;
            textBox1.Text = "SEU VOTO PARA";
            pictureBox3.Location = new Point(735, -2);
            pictureBox3.Name = "pictureBox3";
            pictureBox3.Size = new Size(295, 92);
            pictureBox3.TabIndex = 17;
            pictureBox3.TabStop = false;
            pictureBox3.Click += pictureBox3_Click;
            textBox2.BackColor = Color.FromArgb(255, 224, 192);
            textBox2.BorderStyle = BorderStyle.None;
            textBox2.Font = new Font("Arial Black", 18F);
            textBox2.ForeColor = SystemColors.MenuText;
            textBox2.Location = new Point(886, 4);
            textBox2.Name = "textBox2";
            textBox2.Size = new Size(157, 34);
            textBox2.TabIndex = 18;
            textBox2.Text = "JUSTIÇA";
            textBox3.BackColor = Color.FromArgb(255, 224, 192);
            textBox3.BorderStyle = BorderStyle.None;
            textBox3.Font = new Font("Arial Black", 18F);
            textBox3.ForeColor = SystemColors.MenuText;
            textBox3.Location = new Point(854, 38);
            textBox3.Name = "textBox3";
            textBox3.Size = new Size(157, 34);
            textBox3.TabIndex = 19;
            textBox3.Text = "ELEITORAL";
            labelCargoAtual.Location = new Point(0, 0);
            labelCargoAtual.Name = "labelCargoAtual";
            labelCargoAtual.Size = new Size(100, 23);
            labelCargoAtual.TabIndex = 0;
            BackColor = Color.FromArgb(255, 224, 192);
            ClientSize = new Size(1028, 400);
            Controls.Add(labelCargoAtual);
            Controls.Add(textBox3);
            Controls.Add(textBox2);
            Controls.Add(pictureBox3);
            Controls.Add(textBox1);
            Controls.Add(textBoxDisplay);
            Controls.Add(pictureBox2);
            Controls.Add(button1);
            Controls.Add(button2);
            Controls.Add(button3);
            Controls.Add(button4);
            Controls.Add(button5);
            Controls.Add(button6);
            Controls.Add(button7);
            Controls.Add(button8);
            Controls.Add(button9);
            Controls.Add(button0);
            Controls.Add(buttonBranco);
            Controls.Add(buttonCorrige);
            Controls.Add(buttonConfirma);
            Controls.Add(pictureBox1);
            FormBorderStyle = FormBorderStyle.FixedSingle;
            MaximizeBox = false;
            Name = "Form1";
            Text = "Simulação de Urna Eletrônica";
            ((System.ComponentModel.ISupportInitialize)pictureBox1).EndInit();
            ((System.ComponentModel.ISupportInitialize)pictureBox2).EndInit();
            ((System.ComponentModel.ISupportInitialize)pictureBox3).EndInit();
            ResumeLayout(false);
            PerformLayout();
        }

        private System.Windows.Forms.TextBox textBoxDisplay;
        private System.Windows.Forms.Button button1;
        private System.Windows.Forms.Button button2;
        private System.Windows.Forms.Button button3;
        private System.Windows.Forms.Button button4;
        private System.Windows.Forms.Button button5;
        private System.Windows.Forms.Button button6;
        private System.Windows.Forms.Button button7;
        private System.Windows.Forms.Button button8;
        private System.Windows.Forms.Button button9;
        private System.Windows.Forms.Button button0;
        private System.Windows.Forms.Button buttonBranco;
        private System.Windows.Forms.Button buttonCorrige;
        private System.Windows.Forms.Button buttonConfirma;
        private PictureBox pictureBox1;
        private PictureBox pictureBox2;
        private TextBox textBox1;
        private PictureBox pictureBox3;
        private TextBox textBox2;
        private TextBox textBox3;
        private Label labelCargoAtual;
    }
}
